Need To See All: TextureList Class Reference
TextureList Class Reference
#include <general.h>
Public Member Functions
TextureList ()
TextureList (std::string filePath)
void loadTextures (std::string filePath)
void showErrors (std::string outfilen="")
sf::Texture * getTexture (std::string textureID)
Static Public Member Functions
static TextureList * getGeneralTextureList ()
Detailed Description
Definition at line 64 of file general.h.
Constructor & Destructor Documentation
TextureList::TextureList () inline
Definition at line 67 of file general.h.
TextureList::TextureList (std::string filePath)
Note
check 1
Definition at line 72 of file general.cpp.
Member Function Documentation
TextureList * TextureList::getGeneralTextureList () static
Definition at line 11 of file general.cpp.
Referenced by WindowEntity::addTexture(), and main().
sf::Texture * TextureList::getTexture (std::string textureID)
Definition at line 127 of file general.cpp.
Referenced by WindowEntity::addTexture().
void TextureList::loadTextures (std::string filePath)
Note
check 1
Definition at line 92 of file general.cpp.
Referenced by main(), and TextureList().
void TextureList::showErrors (std::string outfilen = "")
Note
check 1
Definition at line 77 of file general.cpp.
Referenced by loadTextures().
The documentation for this class was generated from the following files:
src/General/general.h
src/General/general.cpp