Need To See All: Player Class Reference
Player Class Reference
#include <entity.h>
Public Types
enum Direction { Up, Down, Front, Back }
Public Member Functions
Player ()
Player (std::string name, unsigned int priority, std::string textureID="")
Player (std::string name, unsigned int priority, unsigned int width, int positionY, std::string textureID="")
void actualiser (NtsaWindow *window)
void moveSomewere (Direction direction)
void stabilize ()
void stopMoving ()
void setSpeedUpDown (int speed=3)
void setSpeedFront (int speed=4)
Public Member Functions inherited from WindowEntity
WindowEntity ()
WindowEntity (std::string name, unsigned int priority, std::string textureID="")
void addTexture (std::string textureID)
void setZone (int newPosX, int newPosY, int newWidth=0, int newHeight=0)
void setWidthHeight (int newWidth, int newHeight)
void setPosition (int newPosX, int newPosY)
std::string getName ()
Additional Inherited Members
Protected Member Functions inherited from WindowEntity
void actuateSprite (unsigned int spriteLocation=0, unsigned int textureLocation=0)
Protected Attributes inherited from WindowEntity
std::vector< sf::Sprite * > m_sprites
std::vector< sf::Texture * > m_textures
std::string m_name ="Robert Paulson"
unsigned int m_priority =PRIORITY_CENTER
int m_posX =23
int m_posY =23
int m_height =23
int m_width =23
Detailed Description
Definition at line 7 of file entity.h.
Member Enumeration Documentation
enum Player::Direction
Enumerator
Up
Down
Front
Back
Definition at line 10 of file entity.h.
Constructor & Destructor Documentation
Player::Player ()
Definition at line 6 of file entity.cpp.
Player::Player (std::string name, unsigned int priority, std::string textureID = "")
Definition at line 12 of file entity.cpp.
Player::Player (std::string name, unsigned int priority, unsigned int width, int positionY, std::string textureID = "")
Definition at line 19 of file entity.cpp.
Member Function Documentation
void Player::actualiser (NtsaWindow * window)
Definition at line 26 of file entity.cpp.
Referenced by NtsaWindow::actualize().
void Player::moveSomewere (Direction direction)
Definition at line 52 of file entity.cpp.
Referenced by NtsaWindow::actualize().
void Player::setSpeedFront (int speed = 4)
void Player::setSpeedUpDown (int speed = 3)
void Player::stabilize ()
Definition at line 66 of file entity.cpp.
Referenced by NtsaWindow::actualize().
void Player::stopMoving ()
Definition at line 60 of file entity.cpp.
The documentation for this class was generated from the following files:
src/Game/entity.h
src/Game/entity.cpp