Need To See All: NtsaWindow Class Reference
NtsaWindow Class Reference
#include <ntsa.h>
Public Types
enum PosNames { X, Y }
Public Member Functions
NtsaWindow (Player player)
NtsaWindow (sf::VideoMode mode, const sf::String &title, sf::Uint32 style=sf::Style::Default, const sf::ContextSettings &settings=sf::ContextSettings())
NtsaWindow (sf::WindowHandle handle, const sf::ContextSettings &settings=sf::ContextSettings())
float getRelativePos (PosNames, int factor)
void setPlayer (Player &player)
void addButton (Button)
void actualize ()
void doAction (std::string action)
int getSize (PosNames pos)
sf::RenderWindow * getRenderWindow ()
std::pair< int, int > getWidthHeight ()
void close ()
void draw (sf::Sprite *sprite)
bool isOpen ()
Detailed Description
Definition at line 10 of file ntsa.h.
Member Enumeration Documentation
enum NtsaWindow::PosNames
Enumerator
X
Y
Definition at line 13 of file ntsa.h.
Constructor & Destructor Documentation
NtsaWindow::NtsaWindow (Player player)
Definition at line 3 of file ntsa.cpp.
NtsaWindow::NtsaWindow (sf::VideoMode mode, const sf::String & title, sf::Uint32 style = sf::Style::Default, const sf::ContextSettings & settings = sf::ContextSettings())
Definition at line 8 of file ntsa.cpp.
NtsaWindow::NtsaWindow (sf::WindowHandle handle, const sf::ContextSettings & settings = sf::ContextSettings())
Definition at line 14 of file ntsa.cpp.
Member Function Documentation
void NtsaWindow::actualize ()
Definition at line 49 of file ntsa.cpp.
Referenced by main().
void NtsaWindow::addButton (Button button)
Definition at line 24 of file ntsa.cpp.
Referenced by main().
void NtsaWindow::close () inline
Definition at line 31 of file ntsa.h.
void NtsaWindow::doAction (std::string action)
Definition at line 29 of file ntsa.cpp.
Referenced by actualize().
void NtsaWindow::draw (sf::Sprite * sprite) inline
Definition at line 32 of file ntsa.h.
float NtsaWindow::getRelativePos (PosNames pos, int factor)
Definition at line 35 of file ntsa.cpp.
Referenced by main().
sf::RenderWindow* NtsaWindow::getRenderWindow () inline
Definition at line 26 of file ntsa.h.
int NtsaWindow::getSize (PosNames pos)
Definition at line 42 of file ntsa.cpp.
Referenced by Player::actualiser().
std::pair<int, int> NtsaWindow::getWidthHeight ()
bool NtsaWindow::isOpen () inline
Definition at line 33 of file ntsa.h.
Referenced by main().
void NtsaWindow::setPlayer (Player & player)
Definition at line 19 of file ntsa.cpp.
Referenced by main().
The documentation for this class was generated from the following files:
src/Game/ntsa.h
src/Game/ntsa.cpp